services:
  _defaults:
    autowire: true
    autoconfigure: true

  Codememory\ApiBundle\Decorator\ControllerArgumentValueResolver\:
    resource: '../../Decorator/ControllerArgumentValueResolver/*Handler.php'
    autowire: true
    tags:
      - { name: codememory.decorator, type: controller_argument_value_resolver }

  Codememory\ApiBundle\Decorator\ControllerArgument\:
    resource: '../../Decorator/ControllerArgument/*Handler.php'
    autowire: true
    tags:
      - { name: codememory.decorator, type: controller_argument }