services:
  Codememory\ApiBundle\EventListener\KernelControllerViewEventListener:
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

  Codememory\ApiBundle\EventListener\KernelException\HttpExceptionEventListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }