services:
  _defaults:
    autowire: true
    autoconfigure: true

  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

  Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactoryInterface:
    class: Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactory

  # Event Listeners
  Codememory\ApiBundle\EventListener\KernelControllerViewEventListener:
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

  Codememory\ApiBundle\EventListener\KernelController\AttributeControllerEventListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  Codememory\ApiBundle\EventListener\KernelControllerArguments\EventDispatchArgumentEventListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller_arguments, method: onKernelControllerArguments }

  Codememory\ApiBundle\EventListener\ControllerArgument\AttributeHandlerEventListener:
    tags:
      - { name: kernel.event_listener, event: codememory.controller_argument, method: onControllerArgument }

  # Decorators
  Codememory\ApiBundle\Decorator\ControllerArgumentValueResolver\:
    resource: '../../Decorator/ControllerArgumentValueResolver/*Handler.php'
    autowire: true
    tags:
      - { name: codememory.decorator.controller_argument_value_resolver }

  Codememory\ApiBundle\Decorator\ControllerArgument\:
    resource: '../../Decorator/ControllerArgument/*Handler.php'
    autowire: true
    tags:
      - { name: codememory.decorator.controller_argument }

  Codememory\ApiBundle\Decorator\DTO\HttpPatchHandler:
    autowire: true
    tags:
      - { name: codememory.dto.decorator }

  Codememory\ApiBundle\Decorator\DTO\ToEntityHandler:
    autowire: true
    tags:
      - { name: codememory.dto.decorator }

  Codememory\ApiBundle\Decorator\DTO\ToListEntitiesHandler:
    autowire: true
    tags:
      - { name: codememory.dto.decorator }
  
  Codememory\ApiBundle\Decorator\DTO\FileExpectedHandler:
    tags:
      - { name: codememory.dto.decorator }

  Codememory\ApiBundle\Decorator\ERC\CallbackWithEntityRepositoryHandler:
    autowire: true
    tags:
      - { name: codememory.erc.decorator }

  # Commands
  Codememory\ApiBundle\Command\OpenSSLKeyCommand:
    tags:
      - { name: console.command, command: 'codememory:openssl:generate-key' }